---
# set the following RHDP instance specific variables
cluster_generic_password: "xyz123" 
cluster_guid: "xyz123"   
cluster_region: "us-east-2"

# default namespaces
gitlab_namespace: "gitlab"
backstage_namespace: "backstage"
vault_namespace: "vault"
quay_namespace: "quay-enterprise"

# lab namespaces
jumpstarter_namespace: jumpstarter-lab
jumpstarter_qemu_exporter_namespace: jumpstarter-qemu-exporter
outpost_namespace: outpost
rhadp_namespace: rhadp

# jumpstarter
jumpstarter_helm_repo: quay.io/jumpstarter-dev/helm
jumpstarter_helm_repo_version: "0.5.0-117-g1b98390"

# developer hub
rhdh_title: "Red Hat Automotive Development Platform"

# developer hub templates
templates_repo_group: "rhdh"
templates_repo_name: "lab2255-templates"
templates_repo_url: "https://github.com/rhadp-example-repos/lab2255-templates"
templates_repo_branch: "develop"
